%YAML:1.0

#common parameters
image_topic: "/visensor/left/image_raw"
output_path: "/home/lincoln/output/"

#camera calibration 
model_type: PINHOLE
camera_name: /visensor/left
image_width: 752
image_height: 480
distortion_parameters:
   k1: -0.2886519243
   k2: 0.08251010503
   p1: -0.0003745841
   p2: -9.908178225e-05
projection_parameters:
   fx: 465.66479689
   fy: 465.53104947
   cx: 373.17652925
   cy: 232.29333312


#feature traker paprameters
max_cnt: 200            # max feature number in feature tracking
min_dist: 10            # min distance between two features 
freq: 25                 # frequence (Hz) of publish tracking result. At least 10Hz for good estimation. If set 0, the frequence will be same as raw image 
F_threshold: 1.0        # ransac threshold (pixel)
show_track: 1           # publish tracking image as topic
equalize: 1             # if image is too dark or light, trun on equalize to find enough features
fisheye: 0              # if using fisheye, trun on it. A circle mask will be loaded to remove edge noisy points

                       # initial value of time offset. unit: s. readed image clock + td = real image clock (IMU clock)

#rolling shutter parameters
rolling_shutter: 0                  # 0: global shutter camera, 1: rolling shutter camera
rolling_shutter_tr: 0               # unit: s. rolling shutter read out time per frame (from data sheet). 


